---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  tasks:
    - name: Sync CFT templates to S3
      s3_sync:
        bucket: neccdc2018
        file_root: templates/
    - name: launch competition infrastructure
      cloudformation:
        stack_name: "NECCDC2018-BlueTeam{{ timestamp }}"
        state: "present"
        region: "us-east-1"
        disable_rollback: false
        template: "templates/main-infrastructure.json"
        template_parameters:
          pKeyName: "neccdc2"
          pCreateVPCManagement: "no"
          pCreateProductionHA: "no"
          pCreateManagementHA: "no"
          pCreateCloudTrail: "no"
# Set stack4URL to "" to turn off creating any instances          
#          stack4URL: "https://s3.amazonaws.com/neccdc2018/stack4-application.json"
          stack4URL: ""
        tags:
           Stack: "blueteam_infrastructure"

