# FILENAME
# delete-team-stack.yml
#
# DESCRIPTION
# Take down a team entry in the event
# 
# REQUIREMENTS
#
# EXECUTE
# ansible-playbook ./playbooks/delete-team-stack.yml  --extra-vars "campus=XXX stack=YYY"
#
---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
     team_name: "{{ campus | default('default') }}"
     stack_type: "{{ stack | default('NECCDC2018') }}"

  tasks:
     - name: Delete stack {{ stack_type }} for {{ team_name }}
       cloudformation:
          stack_name: "{{ stack_type }}"
          aws_access_key: "{{ lookup('ini', 'aws_access_key_id section={{ team_name }} file=~/.aws/credentials') }}"
          aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section={{ team_name }} file=~/.aws/credentials') }}"
          state: "absent"
          region: "us-east-1"
